### Get all products
GET http://localhost:3000/products

### Get a single product
GET http://localhost:3000/products/6055fe468fab643a4c3f2e4b

### Create a product
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "IPhone X",
    "price": 7500,
    "category": "606a086f852ce20d101198f9"
}

### Delete product
DELETE http://localhost:3000/products/60563bf327bc5a15f80d0eb1

### Update product
PUT http://localhost:3000/products/6058d2825a825301fc35fa31
Content-Type: application/json

{
    "name": "iMac 2",
    "price": 11999
}

###
GET http://localhost:3000/asd

### TEST
POST http://localhost:3000/test
Content-Type: application/json
{
    "name": "iPad",
    "price": 999
}


// Category

### Get all categories
GET http://localhost:3000/categories

### Get a single category
GET http://localhost:3000/categories/6055fe468fab643a4c3f2e4b

### Create a category
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Tablet"
}

### Get all products
GET http://localhost:3000/products/category/606a082a852ce20d101198f8